"""init commit

Revision ID: 3a8b7c8118a7
Revises: 
Create Date: 2020-07-15 11:24:22.182628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b7c8118a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色Id'),
    sa.Column('role_name', sa.VARCHAR(length=64), nullable=True, comment='角色名字'),
    sa.Column('permission_id', sa.BIGINT(), nullable=True, comment='权限ID'),
    sa.Column('re_mark', sa.VARCHAR(length=128), nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('id', 'role_id'),
    comment='管理员角色'
    )
    op.create_index(op.f('ix_admin_role_id'), 'admin_role', ['id'], unique=False)
    op.create_index(op.f('ix_admin_role_role_id'), 'admin_role', ['role_id'], unique=False)
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.VARCHAR(length=16), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True, comment='管理员昵称'),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True, comment='管理员头像'),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=True, comment='邮箱是否激活 0=未激活 1=激活'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色表'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='管理员表'
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_id'), 'admin_user', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_phone'), 'admin_user', ['phone'], unique=True)
    op.create_table('mall_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True, comment='用户昵称'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('country_id', sa.Integer(), nullable=True, comment='国家Id'),
    sa.Column('province_id', sa.Integer(), nullable=True, comment='省id'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='市id'),
    sa.Column('district_id', sa.Integer(), nullable=True, comment='区id'),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True, comment='详细地址'),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True, comment='手机号'),
    sa.Column('is_default', sa.SmallInteger(), server_default='0', nullable=True, comment='是否默认地址'),
    sa.PrimaryKeyConstraint('id'),
    comment='地址表'
    )
    op.create_index(op.f('ix_mall_address_id'), 'mall_address', ['id'], unique=False)
    op.create_table('mall_banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('prc', sa.VARCHAR(length=256), nullable=True, comment='图片url'),
    sa.Column('link', sa.VARCHAR(length=256), nullable=True, comment='跳转地址(或者关联商品)'),
    sa.Column('goods_id', sa.VARCHAR(length=128), nullable=True, comment='关联商品'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.Column('banner_position', sa.VARCHAR(length=64), nullable=True, comment='轮播图位置 默认首页 首页home 个人中心profile '),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mall_banner_id'), 'mall_banner', ['id'], unique=False)
    op.create_table('mall_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('goods_id', sa.VARCHAR(length=20), nullable=True, comment='商品id'),
    sa.Column('goods_num', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='零售价,单价'),
    sa.PrimaryKeyConstraint('id'),
    comment='购物车'
    )
    op.create_index(op.f('ix_mall_cart_goods_id'), 'mall_cart', ['goods_id'], unique=False)
    op.create_index(op.f('ix_mall_cart_id'), 'mall_cart', ['id'], unique=False)
    op.create_index(op.f('ix_mall_cart_user_id'), 'mall_cart', ['user_id'], unique=False)
    op.create_table('mall_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True, comment='分类名称'),
    sa.Column('front_desc', sa.VARCHAR(length=256), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父id'),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True, comment='排序'),
    sa.Column('icon_url', sa.VARCHAR(length=256), nullable=True, comment='分类显示icon'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mall_category_id'), 'mall_category', ['id'], unique=False)
    op.create_index(op.f('ix_mall_category_parent_id'), 'mall_category', ['parent_id'], unique=False)
    op.create_table('mall_except_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('content', sa.VARCHAR(length=256), nullable=True, comment='地区名称'),
    sa.Column('area', sa.VARCHAR(length=256), nullable=True, comment='地区地区id ,隔开如 6,30,31,32'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mall_except_area_id'), 'mall_except_area', ['id'], unique=False)
    op.create_table('mall_freight_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True, comment='运费模版名称'),
    sa.Column('package_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='包装费用'),
    sa.Column('freight_type', sa.SmallInteger(), nullable=True, comment='0=按件 1=按重量'),
    sa.PrimaryKeyConstraint('id'),
    comment='运费模版'
    )
    op.create_index(op.f('ix_mall_freight_template_id'), 'mall_freight_template', ['id'], unique=False)
    op.create_table('mall_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('goods_id', sa.VARCHAR(length=128), nullable=True, comment='商品id'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类id'),
    sa.Column('is_on_sale', sa.Integer(), nullable=True, comment='是否售卖 0=否 1=是'),
    sa.Column('goods_name', sa.VARCHAR(length=64), nullable=True, comment='商品名称'),
    sa.Column('goods_number', sa.Integer(), nullable=True, comment='商品数量'),
    sa.Column('specification_id', sa.Integer(), nullable=True, comment='商品规格id'),
    sa.Column('keywords', sa.VARCHAR(length=256), nullable=True, comment='商品关键字'),
    sa.Column('sell_volume', sa.Integer(), nullable=True, comment='销售量'),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='零售价,单价'),
    sa.Column('min_retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='最低零售价'),
    sa.Column('cost_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='成本价'),
    sa.Column('min_cost_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='最低成本价'),
    sa.Column('goods_brief', sa.VARCHAR(length=256), nullable=True, comment='商品简介'),
    sa.Column('goods_desc', sa.TEXT(), nullable=True, comment='商品描述'),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True, comment='排序'),
    sa.Column('is_index', sa.SmallInteger(), nullable=True),
    sa.Column('is_new', sa.SmallInteger(), nullable=True, comment='是否新品推荐'),
    sa.Column('goods_unit', sa.VARCHAR(length=45), nullable=True, comment='商品单位'),
    sa.Column('list_prc_banner', sa.VARCHAR(length=256), nullable=True, comment='商品banner'),
    sa.Column('list_pic_url', sa.VARCHAR(length=256), nullable=True, comment='商品列表图'),
    sa.Column('freight_template_id', sa.SmallInteger(), nullable=True, comment='配运模版id'),
    sa.Column('freight_type', sa.VARCHAR(length=256), nullable=True, comment='配运类型'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品详情'
    )
    op.create_index(op.f('ix_mall_goods_category_id'), 'mall_goods', ['category_id'], unique=False)
    op.create_index(op.f('ix_mall_goods_goods_id'), 'mall_goods', ['goods_id'], unique=True)
    op.create_index(op.f('ix_mall_goods_goods_number'), 'mall_goods', ['goods_number'], unique=False)
    op.create_index(op.f('ix_mall_goods_id'), 'mall_goods', ['id'], unique=False)
    op.create_index(op.f('ix_mall_goods_sort_order'), 'mall_goods', ['sort_order'], unique=False)
    op.create_index(op.f('ix_mall_goods_specification_id'), 'mall_goods', ['specification_id'], unique=False)
    op.create_table('mall_goods_gallery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('goods_id', sa.SmallInteger(), nullable=True, comment='商品id'),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_desc', sa.VARCHAR(length=64), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True, comment='排序'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品列表'
    )
    op.create_index(op.f('ix_mall_goods_gallery_goods_id'), 'mall_goods_gallery', ['goods_id'], unique=False)
    op.create_index(op.f('ix_mall_goods_gallery_id'), 'mall_goods_gallery', ['id'], unique=False)
    op.create_table('mall_goods_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('keyword', sa.VARCHAR(length=128), nullable=True, comment='关键词'),
    sa.Column('is_hot', sa.SmallInteger(), nullable=True, comment='是否热点'),
    sa.Column('is_default', sa.SmallInteger(), nullable=True, comment='是否热点'),
    sa.Column('is_show', sa.SmallInteger(), nullable=True, comment='是否展示'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('scheme_url', sa.VARCHAR(length=128), nullable=True, comment='关键词跳转链接'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品关键词'
    )
    op.create_index(op.f('ix_mall_goods_keywords_id'), 'mall_goods_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_mall_goods_keywords_is_hot'), 'mall_goods_keywords', ['is_hot'], unique=False)
    op.create_table('mall_goods_specification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('good_id', sa.VARCHAR(length=128), nullable=True, comment='对应商品id'),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True, comment='商品规格名称 如重量 长度 颜色'),
    sa.Column('unit', sa.VARCHAR(length=16), nullable=True, comment='规格单位 如斤 克'),
    sa.Column('memo', sa.VARCHAR(length=64), nullable=True, comment='补充说明 如每袋5个装'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='库存'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品规格'
    )
    op.create_index(op.f('ix_mall_goods_specification_id'), 'mall_goods_specification', ['id'], unique=False)
    op.create_table('mall_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('order_id', sa.VARCHAR(length=20), nullable=True, comment='订单id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户Id'),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True, comment='手机号'),
    sa.Column('order_status', sa.SmallInteger(), nullable=True, comment='订单状态 101：未付款、102：已取消、103已取消(系统)、201：已付款、202：订单取消，退款中、203：已退款、301：已发货、302：已收货、303：已收货(系统)、401：已完成、801：拼团中,未付款、802：拼团中,已付款'),
    sa.Column('offline_pay', sa.Integer(), nullable=True, comment='线下支付订单标志'),
    sa.Column('shipping_status', sa.Integer(), nullable=True, comment='发货状态'),
    sa.Column('consignee', sa.VARCHAR(length=64), nullable=True, comment='支付状态'),
    sa.Column('country_id', sa.Integer(), nullable=True, comment='国家'),
    sa.Column('province_id', sa.Integer(), nullable=True, comment='省'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='市'),
    sa.Column('district_id', sa.Integer(), nullable=True, comment='区'),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True, comment='详细地址'),
    sa.Column('postscript', sa.VARCHAR(length=128), nullable=True, comment='用户留言备注'),
    sa.Column('admin_memo', sa.VARCHAR(length=128), nullable=True, comment='管理员留言备注'),
    sa.Column('print_status', sa.Integer(), nullable=True, comment='打印状态'),
    sa.Column('print_info', sa.VARCHAR(length=128), nullable=True, comment='打印信息'),
    sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='免邮的商品的邮费，这个在退款时不能退给客户'),
    sa.Column('pay_name', sa.VARCHAR(length=128), nullable=True, comment='支付名称'),
    sa.Column('pay_id', sa.VARCHAR(length=255), nullable=True, comment='支付ID'),
    sa.Column('pay_status', sa.Integer(), nullable=True, comment='支付状态'),
    sa.Column('change_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='0没改价，不等于0改过价格，这里记录原始的价格'),
    sa.Column('actual_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='实际需要支付的金额'),
    sa.Column('order_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='订单总价'),
    sa.Column('goods_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='商品总价'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('shipping_time', sa.DateTime(), nullable=True, comment='发货时间'),
    sa.Column('confirm_time', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('dealdone_time', sa.DateTime(), nullable=True, comment='成交时间，用户评论或自动好评时间'),
    sa.Column('freight_price', sa.Integer(), nullable=True, comment='配送费用'),
    sa.Column('express_value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='顺丰保价金额'),
    sa.Column('remark', sa.VARCHAR(length=256), nullable=True),
    sa.Column('order_type', sa.SmallInteger(), nullable=True, comment='订单类型：0普通，1秒杀，2团购，3返现订单,7充值，8会员'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单表'
    )
    op.create_index(op.f('ix_mall_order_id'), 'mall_order', ['id'], unique=False)
    op.create_index(op.f('ix_mall_order_order_id'), 'mall_order', ['order_id'], unique=True)
    op.create_index(op.f('ix_mall_order_order_status'), 'mall_order', ['order_status'], unique=False)
    op.create_index(op.f('ix_mall_order_pay_status'), 'mall_order', ['pay_status'], unique=False)
    op.create_index(op.f('ix_mall_order_user_id'), 'mall_order', ['user_id'], unique=False)
    op.create_table('mall_order_express',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('order_id', sa.VARCHAR(length=20), nullable=True, comment='订单id'),
    sa.Column('shipper_id', sa.VARCHAR(length=20), nullable=True, comment='物流公司Id'),
    sa.Column('shipper_name', sa.VARCHAR(length=20), nullable=True, comment='物流公司名称'),
    sa.Column('shipper_code', sa.VARCHAR(length=20), nullable=True, comment='物流公司代码'),
    sa.Column('logistic_code', sa.VARCHAR(length=20), nullable=True, comment='快递单号'),
    sa.Column('traces', sa.VARCHAR(length=20), nullable=True, comment='物流跟踪信息'),
    sa.Column('is_finish', sa.SmallInteger(), nullable=True, comment='是否完成 0否 1是'),
    sa.Column('request_count', sa.Integer(), nullable=True, comment='总查询次数'),
    sa.Column('request_time', sa.DateTime(), nullable=True, comment='最近一次查询时间'),
    sa.Column('express_type', sa.Integer(), nullable=True, comment='快递类型'),
    sa.Column('region_code', sa.Integer(), nullable=True, comment='快递的地区编码，如杭州571'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单物流表'
    )
    op.create_index(op.f('ix_mall_order_express_id'), 'mall_order_express', ['id'], unique=False)
    op.create_index(op.f('ix_mall_order_express_order_id'), 'mall_order_express', ['order_id'], unique=False)
    op.create_table('mall_order_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('order_id', sa.VARCHAR(length=20), nullable=True, comment='订单id'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('goods_id', sa.VARCHAR(length=20), nullable=True, comment='商品id'),
    sa.Column('goods_name', sa.VARCHAR(length=20), nullable=True, comment='商品名称'),
    sa.Column('goods_aka', sa.VARCHAR(length=20), nullable=True, comment='商品别称'),
    sa.Column('number', sa.SmallInteger(), nullable=True, comment='数量'),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='零售价'),
    sa.Column('goods_specifition_name_value', sa.VARCHAR(length=256), nullable=True, comment='规格'),
    sa.Column('goods_specifition_ids', sa.VARCHAR(length=256), nullable=True, comment='商品规格id'),
    sa.Column('list_pic_url', sa.VARCHAR(length=256), nullable=True, comment='商品图片'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单商品表'
    )
    op.create_index(op.f('ix_mall_order_goods_goods_id'), 'mall_order_goods', ['goods_id'], unique=False)
    op.create_index(op.f('ix_mall_order_goods_id'), 'mall_order_goods', ['id'], unique=False)
    op.create_index(op.f('ix_mall_order_goods_order_id'), 'mall_order_goods', ['order_id'], unique=False)
    op.create_table('mall_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True, comment='父id'),
    sa.Column('region_name', sa.VARCHAR(length=128), nullable=True, comment='地区名称'),
    sa.Column('region_type', sa.SmallInteger(), nullable=True, comment='地区类型'),
    sa.Column('agency_id', sa.SmallInteger(), nullable=True),
    sa.Column('area', sa.VARCHAR(length=64), nullable=True, comment='方位，根据这个定运费'),
    sa.Column('area_code', sa.VARCHAR(length=8), nullable=True, comment='方位代码'),
    sa.Column('far_area', sa.SmallInteger(), nullable=True, comment='偏远地区'),
    sa.PrimaryKeyConstraint('id'),
    comment='地区'
    )
    op.create_index(op.f('ix_mall_region_agency_id'), 'mall_region', ['agency_id'], unique=False)
    op.create_index(op.f('ix_mall_region_id'), 'mall_region', ['id'], unique=False)
    op.create_index(op.f('ix_mall_region_parent_id'), 'mall_region', ['parent_id'], unique=False)
    op.create_table('mall_search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('keyword', sa.VARCHAR(length=64), nullable=True, comment='搜索关键词'),
    sa.Column('search_origin', sa.SmallInteger(), server_default='1', nullable=True, comment='搜索来源 1=小程序 2=APP 3=PC'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索记录'
    )
    op.create_index(op.f('ix_mall_search_history_id'), 'mall_search_history', ['id'], unique=False)
    op.create_index(op.f('ix_mall_search_history_user_id'), 'mall_search_history', ['user_id'], unique=False)
    op.create_table('mall_shipper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('shipper_name', sa.VARCHAR(length=128), nullable=True, comment='物流公司名称'),
    sa.Column('shipper_code', sa.VARCHAR(length=128), nullable=True, comment='物流公司代码'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('month_code', sa.VARCHAR(length=16), nullable=True, comment='月份'),
    sa.Column('customer_name', sa.VARCHAR(length=16), nullable=True, comment='用户名'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.PrimaryKeyConstraint('id'),
    comment='快递信息'
    )
    op.create_index(op.f('ix_mall_shipper_id'), 'mall_shipper', ['id'], unique=False)
    op.create_table('mall_site_notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.Column('content', sa.VARCHAR(length=256), nullable=True, comment='全局消息通知'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='站点消息'
    )
    op.create_index(op.f('ix_mall_site_notice_id'), 'mall_site_notice', ['id'], unique=False)
    op.create_table('mall_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True, comment='用户昵称(显示用可更改)'),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True, comment='用户名(不可更改)'),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True, comment='用户头像'),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('phone', sa.VARCHAR(length=16), nullable=True, comment='手机号'),
    sa.Column('gender', sa.SmallInteger(), server_default='0', nullable=True, comment='性别 0=未知 1=男 2=女'),
    sa.Column('register_time', sa.DateTime(), nullable=True, comment='注册事件'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='上次登录时间'),
    sa.Column('last_login_ip', sa.VARCHAR(length=64), nullable=True, comment='上次登录IP'),
    sa.Column('register_ip', sa.VARCHAR(length=64), nullable=True, comment='注册IP'),
    sa.Column('weixin_openid', sa.VARCHAR(length=64), nullable=True, comment='微信openId'),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True, comment='国家'),
    sa.Column('province', sa.VARCHAR(length=64), nullable=True, comment='省'),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True, comment='市'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_mall_user_id'), 'mall_user', ['id'], unique=False)
    op.create_index(op.f('ix_mall_user_phone'), 'mall_user', ['phone'], unique=True)
    op.create_index(op.f('ix_mall_user_user_id'), 'mall_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mall_user_user_id'), table_name='mall_user')
    op.drop_index(op.f('ix_mall_user_phone'), table_name='mall_user')
    op.drop_index(op.f('ix_mall_user_id'), table_name='mall_user')
    op.drop_table('mall_user')
    op.drop_index(op.f('ix_mall_site_notice_id'), table_name='mall_site_notice')
    op.drop_table('mall_site_notice')
    op.drop_index(op.f('ix_mall_shipper_id'), table_name='mall_shipper')
    op.drop_table('mall_shipper')
    op.drop_index(op.f('ix_mall_search_history_user_id'), table_name='mall_search_history')
    op.drop_index(op.f('ix_mall_search_history_id'), table_name='mall_search_history')
    op.drop_table('mall_search_history')
    op.drop_index(op.f('ix_mall_region_parent_id'), table_name='mall_region')
    op.drop_index(op.f('ix_mall_region_id'), table_name='mall_region')
    op.drop_index(op.f('ix_mall_region_agency_id'), table_name='mall_region')
    op.drop_table('mall_region')
    op.drop_index(op.f('ix_mall_order_goods_order_id'), table_name='mall_order_goods')
    op.drop_index(op.f('ix_mall_order_goods_id'), table_name='mall_order_goods')
    op.drop_index(op.f('ix_mall_order_goods_goods_id'), table_name='mall_order_goods')
    op.drop_table('mall_order_goods')
    op.drop_index(op.f('ix_mall_order_express_order_id'), table_name='mall_order_express')
    op.drop_index(op.f('ix_mall_order_express_id'), table_name='mall_order_express')
    op.drop_table('mall_order_express')
    op.drop_index(op.f('ix_mall_order_user_id'), table_name='mall_order')
    op.drop_index(op.f('ix_mall_order_pay_status'), table_name='mall_order')
    op.drop_index(op.f('ix_mall_order_order_status'), table_name='mall_order')
    op.drop_index(op.f('ix_mall_order_order_id'), table_name='mall_order')
    op.drop_index(op.f('ix_mall_order_id'), table_name='mall_order')
    op.drop_table('mall_order')
    op.drop_index(op.f('ix_mall_goods_specification_id'), table_name='mall_goods_specification')
    op.drop_table('mall_goods_specification')
    op.drop_index(op.f('ix_mall_goods_keywords_is_hot'), table_name='mall_goods_keywords')
    op.drop_index(op.f('ix_mall_goods_keywords_id'), table_name='mall_goods_keywords')
    op.drop_table('mall_goods_keywords')
    op.drop_index(op.f('ix_mall_goods_gallery_id'), table_name='mall_goods_gallery')
    op.drop_index(op.f('ix_mall_goods_gallery_goods_id'), table_name='mall_goods_gallery')
    op.drop_table('mall_goods_gallery')
    op.drop_index(op.f('ix_mall_goods_specification_id'), table_name='mall_goods')
    op.drop_index(op.f('ix_mall_goods_sort_order'), table_name='mall_goods')
    op.drop_index(op.f('ix_mall_goods_id'), table_name='mall_goods')
    op.drop_index(op.f('ix_mall_goods_goods_number'), table_name='mall_goods')
    op.drop_index(op.f('ix_mall_goods_goods_id'), table_name='mall_goods')
    op.drop_index(op.f('ix_mall_goods_category_id'), table_name='mall_goods')
    op.drop_table('mall_goods')
    op.drop_index(op.f('ix_mall_freight_template_id'), table_name='mall_freight_template')
    op.drop_table('mall_freight_template')
    op.drop_index(op.f('ix_mall_except_area_id'), table_name='mall_except_area')
    op.drop_table('mall_except_area')
    op.drop_index(op.f('ix_mall_category_parent_id'), table_name='mall_category')
    op.drop_index(op.f('ix_mall_category_id'), table_name='mall_category')
    op.drop_table('mall_category')
    op.drop_index(op.f('ix_mall_cart_user_id'), table_name='mall_cart')
    op.drop_index(op.f('ix_mall_cart_id'), table_name='mall_cart')
    op.drop_index(op.f('ix_mall_cart_goods_id'), table_name='mall_cart')
    op.drop_table('mall_cart')
    op.drop_index(op.f('ix_mall_banner_id'), table_name='mall_banner')
    op.drop_table('mall_banner')
    op.drop_index(op.f('ix_mall_address_id'), table_name='mall_address')
    op.drop_table('mall_address')
    op.drop_index(op.f('ix_admin_user_phone'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_admin_role_role_id'), table_name='admin_role')
    op.drop_index(op.f('ix_admin_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    # ### end Alembic commands ###
