"""add role field

Revision ID: 9e7df46ef46a
Revises: c37f1ec47c03
Create Date: 2020-07-11 11:42:13.330505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7df46ef46a'
down_revision = 'c37f1ec47c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role', sa.Column('re_mark', sa.String(length=128), nullable=True, comment='备注信息'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role', 're_mark')
    # ### end Alembic commands ###
