"""ad avatar

Revision ID: c37f1ec47c03
Revises: a6563878a3ad
Create Date: 2020-07-11 09:54:46.487869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c37f1ec47c03'
down_revision = 'a6563878a3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('avatar', sa.String(length=256), nullable=True, comment='用户头像'))
    op.alter_column('admin_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='邮箱是否激活',
               existing_comment='是否激活',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否激活',
               existing_comment='邮箱是否激活',
               existing_nullable=True)
    op.drop_column('admin_user', 'avatar')
    # ### end Alembic commands ###
